# Generated by Django 2.1.3 on 2018-12-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0002_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_number',
            field=models.CharField(default='', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
