# Generated by Django 2.1.3 on 2018-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp1', '0003_customer_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='doc_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
